function [voltage] = calculate_voltage(r)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% calculate_voltage: Helper function used for calculating the voltage for
% specific charge configuration. NOTE: Must iterate over all charge pairs, 
% and therefore should not be used to calculate voltage for each timestep.
% Should only be used for the first and last timestep, voltage for all 
% other timesteps is calculated within charges.m, while calculating the
% coloumb interaction term, so as not to have to iterate over all charges
% again.
%
% Input arguments
%
% r: current positions (nc x 3 array, where nc is the number of
% charges)
%
% Output arguments
%
% voltage: voltage generated by the specific charge configuration (scalar)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    voltage = 0;
    
    nc = size(r, 1); % Find number of charges from dimensions of r
    for i = 2:nc
        for j = 1:(i-1)
            r_ij = r(j, :) - r(i, :);
            voltage = voltage + 1/norm(r_ij);
        end
    end
end

